### ISSUE TITLE
[ENHANCEMENT] Configuration directory

### ISSUE THREAD

**Issue by arwowchu** [Apothicon02/Glowing-Ores#4]
PROPOSAL: Migrating the `glore_(blocks;brightness).json` configuration files from the `.minecraft/mods/` directory to the `.minecraft/config/` directory.
REASONING: Expected feature + tidiness, especially in heavily modded installations

**Comment by HatTrkPatrk** [comment]
+1 it's odd for config files to be in the "mods" JAR directory...

**Comment by Apothicon02** [comment]
Changed in 1.21
