### ISSUE TITLE
Glowing Ores 1.2.0. Destroyed world.

### ISSUE THREAD

**Issue by bons66** [Apothicon02/Glowing-Ores#6]
MC 1.21.1
Fabric 0.15.11
fabric-api-0.92.2+1.20.1 + over 400 mods

Glowing Ores 1.2.0 - WORK FINE. With default config.

When I change config files (in mod folder -???)...
All blocks in world start emit light... No mob spawning... 
Uninstalling mod - not solve problem. Destroyed world.

Edited configs -
[glore_blocks.json](https://github.com/user-attachments/files/16239625/glore_blocks.json)
[glore_brightness.json](https://github.com/user-attachments/files/16239629/glore_brightness.json)

**Comment by Apothicon02** [comment]
If uninstalling the mod didnt fix the problem, it isnt being caused by this mod.
