### ISSUE TITLE
Uncompatibility with Trinkets n Torches

### ISSUE THREAD

**Issue by MrWonderless** [Apothicon02/Glowing-Ores#7]
Makes ores turn really dark when you get close with a Trinkets n Torches light source 
![2024-08-19_12 26 41-min](https://github.com/user-attachments/assets/6749121b-d31b-48c4-9a2f-5a1d966693cb)
![2024-08-19_12 30 57-min](https://github.com/user-attachments/assets/e2967e88-2a22-4d92-8b85-72d0fa14b114)

**Comment by Apothicon02** [comment]
This is an issue with Trinkets n Torches. The ores are just standard light sources like any other light emitting block.
