### ISSUE TITLE
[Enhancement]: Add parameters to adjust color in config

### ISSUE THREAD

**Issue by Torathion** [Apothicon02/Glowing-Ores#8]
I'm currently configuring this mod, because I want to replicate the same glowing ore effect from the [Solas Shader](https://modrinth.com/shader/solas-shader) and I was wondering if you could add parameters to each ore to tweak the glow color. My goal is to give copper ore a more reddish glow than iron.

**Comment by Apothicon02** [comment]
this mod does not handle colors, thats part of the shader
